<?php
/**
 * AttachmentDisplayBodyAirReservationDetailsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Klarna\Checkout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Checkout API V3
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Checkout\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AttachmentDisplayBodyAirReservationDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description AttachmentDisplayBodyAirReservationDetails
 * @package     Klarna\Checkout
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AttachmentDisplayBodyAirReservationDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AttachmentDisplayBodyAirReservationDetails"
     */
    public function testAttachmentDisplayBodyAirReservationDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pnr"
     */
    public function testPropertyPnr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itinerary"
     */
    public function testPropertyItinerary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "insurance"
     */
    public function testPropertyInsurance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passengers"
     */
    public function testPropertyPassengers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "affiliate_name"
     */
    public function testPropertyAffiliateName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
