<?php
/**
 * AttachmentDisplayBodyItineraryTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Klarna\Checkout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Checkout API V3
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Checkout\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AttachmentDisplayBodyItineraryTest Class Doc Comment
 *
 * @category    Class
 * @description AttachmentDisplayBodyItinerary
 * @package     Klarna\Checkout
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AttachmentDisplayBodyItineraryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AttachmentDisplayBodyItinerary"
     */
    public function testAttachmentDisplayBodyItinerary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "departure"
     */
    public function testPropertyDeparture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "departure_city"
     */
    public function testPropertyDepartureCity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "arrival"
     */
    public function testPropertyArrival()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "arrival_city"
     */
    public function testPropertyArrivalCity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "segment_price"
     */
    public function testPropertySegmentPrice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "departure_date"
     */
    public function testPropertyDepartureDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ticket_delivery_method"
     */
    public function testPropertyTicketDeliveryMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ticket_delivery_recipient"
     */
    public function testPropertyTicketDeliveryRecipient()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "passenger_id"
     */
    public function testPropertyPassengerId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "class"
     */
    public function testPropertyClass()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
