<?php
/**
 * DeliveryDetailsV1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Checkout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Checkout API V3
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Checkout;

use PHPUnit\Framework\TestCase;

/**
 * DeliveryDetailsV1Test Class Doc Comment
 *
 * @category    Class
 * @description DeliveryDetailsV1
 * @package     Klarna\Checkout
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeliveryDetailsV1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeliveryDetailsV1"
     */
    public function testDeliveryDetailsV1()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "class"
     */
    public function testPropertyClass()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "timeslot"
     */
    public function testPropertyTimeslot()
    {
    }

    /**
     * Test attribute "pickup_location"
     */
    public function testPropertyPickupLocation()
    {
    }
}
