<?php
/**
 * ProductIdentifiersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\Checkout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Checkout API V3
 *
 * API spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\Checkout;

use PHPUnit\Framework\TestCase;

/**
 * ProductIdentifiersTest Class Doc Comment
 *
 * @category    Class
 * @description ProductIdentifiers
 * @package     Klarna\Checkout
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductIdentifiersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductIdentifiers"
     */
    public function testProductIdentifiers()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "category_path"
     */
    public function testPropertyCategoryPath()
    {
    }

    /**
     * Test attribute "global_trade_item_number"
     */
    public function testPropertyGlobalTradeItemNumber()
    {
    }

    /**
     * Test attribute "manufacturer_part_number"
     */
    public function testPropertyManufacturerPartNumber()
    {
    }
}
