on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@mariadb:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  DRUPAL_CORE_VERSION: 9.4.x
  KLARNA_LIBRARY_NAME: "php-klarna-checkout"
  SYMFONY_DEPRECATIONS_HELPER: disabled
jobs:
  test-contrib:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: ['7.4', '8.0', '8.1']
    container:
      image: ghcr.io/tuutti/drupal-php-docker:${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Make sure all dependencies can be installed
        run: |
          composer config repositories.0 path $GITHUB_WORKSPACE
          composer require tuutti/$KLARNA_LIBRARY_NAME -W
