on:
  push:
  pull_request:
name: CI
env:
  KLARNA_LIBRARY_NAME: "php-klarna-checkout"
jobs:
  test-contrib:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: ['7.4', '8.0', '8.1']
    container:
      image: ghcr.io/tuutti/drupal-php-docker:${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Make sure all dependencies can be installed
        run: composer install

      - name: Make sure we have installed 2.x version of klarna-base
        run: if [[ $(composer show tuutti/php-klarna-base --format=json | jq .versions[0] -r) != "2."* ]]; then exit 1; fi
